name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17
      - run: bun install
      - run: bun run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}